/**
 * 主题配置文件
 * 使用友好的 HEX 颜色格式定义主题
 * 运行 `npm run theme:apply [主题名]` 来应用主题
 */

export const themes = {
  // 默认中性主题
  neutral: {
    name: "中性灰",
    light: {
      background: "#ffffff",
      foreground: "#0a0a0a",
      card: "#ffffff",
      cardForeground: "#0a0a0a",
      popover: "#ffffff",
      popoverForeground: "#0a0a0a",
      primary: "#171717",
      primaryForeground: "#fafafa",
      secondary: "#f5f5f5",
      secondaryForeground: "#171717",
      muted: "#f5f5f5",
      mutedForeground: "#737373",
      accent: "#f5f5f5",
      accentForeground: "#171717",
      destructive: "#ef4444",
      destructiveForeground: "#fafafa",
      border: "#e5e5e5",
      input: "#e5e5e5",
      ring: "#737373",
    },
    dark: {
      background: "#0a0a0a",
      foreground: "#fafafa",
      card: "#171717",
      cardForeground: "#fafafa",
      popover: "#171717",
      popoverForeground: "#fafafa",
      primary: "#fafafa",
      primaryForeground: "#171717",
      secondary: "#262626",
      secondaryForeground: "#fafafa",
      muted: "#262626",
      mutedForeground: "#a3a3a3",
      accent: "#262626",
      accentForeground: "#fafafa",
      destructive: "#7f1d1d",
      destructiveForeground: "#fafafa",
      border: "#262626",
      input: "#262626",
      ring: "#737373",
    },
  },

  // 蓝色主题
  blue: {
    name: "海洋蓝",
    light: {
      background: "#ffffff",
      foreground: "#0f172a",
      card: "#ffffff",
      cardForeground: "#0f172a",
      popover: "#ffffff",
      popoverForeground: "#0f172a",
      primary: "#2563eb",
      primaryForeground: "#f8fafc",
      secondary: "#f1f5f9",
      secondaryForeground: "#0f172a",
      muted: "#f1f5f9",
      mutedForeground: "#64748b",
      accent: "#f1f5f9",
      accentForeground: "#0f172a",
      destructive: "#ef4444",
      destructiveForeground: "#f8fafc",
      border: "#e2e8f0",
      input: "#e2e8f0",
      ring: "#2563eb",
    },
    dark: {
      background: "#020617",
      foreground: "#f8fafc",
      card: "#0f172a",
      cardForeground: "#f8fafc",
      popover: "#0f172a",
      popoverForeground: "#f8fafc",
      primary: "#3b82f6",
      primaryForeground: "#f8fafc",
      secondary: "#1e293b",
      secondaryForeground: "#f8fafc",
      muted: "#1e293b",
      mutedForeground: "#94a3b8",
      accent: "#1e293b",
      accentForeground: "#f8fafc",
      destructive: "#991b1b",
      destructiveForeground: "#f8fafc",
      border: "#1e293b",
      input: "#1e293b",
      ring: "#3b82f6",
    },
  },

  // 绿色主题
  green: {
    name: "森林绿",
    light: {
      background: "#ffffff",
      foreground: "#14532d",
      card: "#ffffff",
      cardForeground: "#14532d",
      popover: "#ffffff",
      popoverForeground: "#14532d",
      primary: "#16a34a",
      primaryForeground: "#f0fdf4",
      secondary: "#f0fdf4",
      secondaryForeground: "#14532d",
      muted: "#f0fdf4",
      mutedForeground: "#16a34a",
      accent: "#dcfce7",
      accentForeground: "#14532d",
      destructive: "#ef4444",
      destructiveForeground: "#f0fdf4",
      border: "#bbf7d0",
      input: "#bbf7d0",
      ring: "#16a34a",
    },
    dark: {
      background: "#052e16",
      foreground: "#f0fdf4",
      card: "#14532d",
      cardForeground: "#f0fdf4",
      popover: "#14532d",
      popoverForeground: "#f0fdf4",
      primary: "#22c55e",
      primaryForeground: "#052e16",
      secondary: "#166534",
      secondaryForeground: "#f0fdf4",
      muted: "#166534",
      mutedForeground: "#86efac",
      accent: "#166534",
      accentForeground: "#f0fdf4",
      destructive: "#991b1b",
      destructiveForeground: "#f0fdf4",
      border: "#166534",
      input: "#166534",
      ring: "#22c55e",
    },
  },

  // 紫色主题
  purple: {
    name: "神秘紫",
    light: {
      background: "#ffffff",
      foreground: "#1e1b4b",
      card: "#ffffff",
      cardForeground: "#1e1b4b",
      popover: "#ffffff",
      popoverForeground: "#1e1b4b",
      primary: "#7c3aed",
      primaryForeground: "#faf5ff",
      secondary: "#f5f3ff",
      secondaryForeground: "#1e1b4b",
      muted: "#f5f3ff",
      mutedForeground: "#6d28d9",
      accent: "#ede9fe",
      accentForeground: "#1e1b4b",
      destructive: "#ef4444",
      destructiveForeground: "#faf5ff",
      border: "#ddd6fe",
      input: "#ddd6fe",
      ring: "#7c3aed",
    },
    dark: {
      background: "#1e1b4b",
      foreground: "#faf5ff",
      card: "#312e81",
      cardForeground: "#faf5ff",
      popover: "#312e81",
      popoverForeground: "#faf5ff",
      primary: "#a78bfa",
      primaryForeground: "#1e1b4b",
      secondary: "#4c1d95",
      secondaryForeground: "#faf5ff",
      muted: "#4c1d95",
      mutedForeground: "#c4b5fd",
      accent: "#4c1d95",
      accentForeground: "#faf5ff",
      destructive: "#991b1b",
      destructiveForeground: "#faf5ff",
      border: "#4c1d95",
      input: "#4c1d95",
      ring: "#a78bfa",
    },
  },

  // 橙色主题
  orange: {
    name: "活力橙",
    light: {
      background: "#ffffff",
      foreground: "#431407",
      card: "#ffffff",
      cardForeground: "#431407",
      popover: "#ffffff",
      popoverForeground: "#431407",
      primary: "#ea580c",
      primaryForeground: "#fff7ed",
      secondary: "#fff7ed",
      secondaryForeground: "#431407",
      muted: "#ffedd5",
      mutedForeground: "#ea580c",
      accent: "#fed7aa",
      accentForeground: "#431407",
      destructive: "#ef4444",
      destructiveForeground: "#fff7ed",
      border: "#fed7aa",
      input: "#fed7aa",
      ring: "#ea580c",
    },
    dark: {
      background: "#431407",
      foreground: "#fff7ed",
      card: "#7c2d12",
      cardForeground: "#fff7ed",
      popover: "#7c2d12",
      popoverForeground: "#fff7ed",
      primary: "#fb923c",
      primaryForeground: "#431407",
      secondary: "#9a3412",
      secondaryForeground: "#fff7ed",
      muted: "#9a3412",
      mutedForeground: "#fdba74",
      accent: "#9a3412",
      accentForeground: "#fff7ed",
      destructive: "#991b1b",
      destructiveForeground: "#fff7ed",
      border: "#9a3412",
      input: "#9a3412",
      ring: "#fb923c",
    },
  },

  // 玫瑰红主题
  rose: {
    name: "玫瑰红",
    light: {
      background: "#ffffff",
      foreground: "#4c0519",
      card: "#ffffff",
      cardForeground: "#4c0519",
      popover: "#ffffff",
      popoverForeground: "#4c0519",
      primary: "#e11d48",
      primaryForeground: "#fff1f2",
      secondary: "#fff1f2",
      secondaryForeground: "#4c0519",
      muted: "#ffe4e6",
      mutedForeground: "#e11d48",
      accent: "#fecdd3",
      accentForeground: "#4c0519",
      destructive: "#ef4444",
      destructiveForeground: "#fff1f2",
      border: "#fecdd3",
      input: "#fecdd3",
      ring: "#e11d48",
    },
    dark: {
      background: "#4c0519",
      foreground: "#fff1f2",
      card: "#881337",
      cardForeground: "#fff1f2",
      popover: "#881337",
      popoverForeground: "#fff1f2",
      primary: "#fb7185",
      primaryForeground: "#4c0519",
      secondary: "#9f1239",
      secondaryForeground: "#fff1f2",
      muted: "#9f1239",
      mutedForeground: "#fda4af",
      accent: "#9f1239",
      accentForeground: "#fff1f2",
      destructive: "#991b1b",
      destructiveForeground: "#fff1f2",
      border: "#9f1239",
      input: "#9f1239",
      ring: "#fb7185",
    },
  },

  // 自定义粉色主题 - 主题色 #ff679a
  custom: {
    name: "自定义粉色",
    light: {
      background: "#ffffff",
      foreground: "#1a1a1a",
      card: "#ffffff",
      cardForeground: "#1a1a1a",
      popover: "#ffffff",
      popoverForeground: "#1a1a1a",
      primary: "#ff679a",              // 主题色
      primaryForeground: "#ffffff",
      secondary: "#fff0f5",
      secondaryForeground: "#1a1a1a",
      muted: "#fff0f5",
      mutedForeground: "#737373",
      accent: "#ffe4ee",
      accentForeground: "#1a1a1a",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#ffcce0",
      input: "#ffcce0",
      ring: "#ff679a",
    },
    dark: {
      background: "#1a1a1a",
      foreground: "#ffffff",
      card: "#262626",
      cardForeground: "#ffffff",
      popover: "#262626",
      popoverForeground: "#ffffff",
      primary: "#ff8bb3",              // 暗色模式稍微浅一点
      primaryForeground: "#1a1a1a",
      secondary: "#3d1f2e",
      secondaryForeground: "#ffffff",
      muted: "#3d1f2e",
      mutedForeground: "#d4d4d4",
      accent: "#4d2638",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#4d2638",
      input: "#4d2638",
      ring: "#ff8bb3",
    },
  },
};

// 默认主题
export const defaultTheme = "neutral";

// 获取主题列表
export function getThemeList() {
  return Object.entries(themes).map(([key, theme]) => ({
    key,
    name: theme.name,
  }));
}
